//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence
    {
        public Absence()
        {
            this.WorkEmployee = new HashSet<WorkEmployee>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public Nullable<int> ReplacementId { get; set; }
        public int AbsenceTypeId { get; set; }
    
        public virtual AbsenceType AbsenceType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<WorkEmployee> WorkEmployee { get; set; }
    }
}
