//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public Candidate()
        {
            this.Skill = new HashSet<Skill>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int AppliedPosition { get; set; }
        public string AboutEmployee { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Skill> Skill { get; set; }
    }
}
