//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDepartment
    {
        public int EmployeeId { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> SubDepartmentId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> AssistantId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual SubDepartment SubDepartment { get; set; }
    }
}
