//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Absence = new HashSet<Absence>();
            this.EmployeeDepartment = new HashSet<EmployeeDepartment>();
            this.EmployeeDepartment1 = new HashSet<EmployeeDepartment>();
            this.EventEmployee = new HashSet<EventEmployee>();
            this.Material = new HashSet<Material>();
            this.WorkEmployee = new HashSet<WorkEmployee>();
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int JobId { get; set; }
        public string WorkPhone { get; set; }
        public int ParlorId { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Absence> Absence { get; set; }
        public virtual Parlor Parlor { get; set; }
        public virtual Person Person { get; set; }
        public virtual Position Position { get; set; }
        public virtual ICollection<EmployeeDepartment> EmployeeDepartment { get; set; }
        public virtual ICollection<EmployeeDepartment> EmployeeDepartment1 { get; set; }
        public virtual ICollection<EventEmployee> EventEmployee { get; set; }
        public virtual ICollection<Material> Material { get; set; }
        public virtual ICollection<WorkEmployee> WorkEmployee { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
