//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventEmployee = new HashSet<EventEmployee>();
            this.MaterialTrening = new HashSet<MaterialTrening>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Description { get; set; }
    
        public virtual TypeEvent TypeEvent { get; set; }
        public virtual ICollection<EventEmployee> EventEmployee { get; set; }
        public virtual ICollection<MaterialTrening> MaterialTrening { get; set; }
    }
}
