//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventEmployee
    {
        public int EventId { get; set; }
        public int Employee { get; set; }
        public bool IsOrganizer { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Event Event { get; set; }
    }
}
