//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.MaterialTrening = new HashSet<MaterialTrening>();
            this.Image = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int SatusId { get; set; }
        public int TypeId { get; set; }
        public string Area { get; set; }
        public Nullable<int> AuthorId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeMaterial TypeMaterial { get; set; }
        public virtual ICollection<MaterialTrening> MaterialTrening { get; set; }
        public virtual ICollection<Image> Image { get; set; }
    }
}
