//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialTrening
    {
        public int EventId { get; set; }
        public int MaterialId { get; set; }
        public int TrainingId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Material Material { get; set; }
        public virtual TrainingCalendar TrainingCalendar { get; set; }
    }
}
