//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingCalendar
    {
        public TrainingCalendar()
        {
            this.MaterialTrening = new HashSet<MaterialTrening>();
        }
    
        public int Id { get; set; }
        public System.DateTime ExceptionDate { get; set; }
        public bool IsEventDay { get; set; }
    
        public virtual ICollection<MaterialTrening> MaterialTrening { get; set; }
    }
}
