//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkEmployee
    {
        public int WorkEmployee_id { get; set; }
        public Nullable<int> WorkingDayId { get; set; }
        public int EmployeeId { get; set; }
        public bool IsWorking { get; set; }
        public Nullable<int> AbsenceId { get; set; }
    
        public virtual Absence Absence { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual WorkingCalendar WorkingCalendar { get; set; }
    }
}
